=== Salmista-94/AgentOnMicrocontroller/src/mobilec.dtd
<!ELEMENT MOBILEC_MESSAGE (MESSAGE)>
<!ELEMENT MESSAGE (MOBILE_AGENT|ENCRYPTED_DATA|ENCRYPTION_DATA)>
<!ATTLIST MESSAGE
  message (MOBILE_AGENT|RETURN_MSG|ENCRYPTED_DATA|ENCRYPTION_INITIALIZE) #REQUIRED>

<!ELEMENT MOBILE_AGENT (AGENT_DATA) >
<!ELEMENT AGENT_DATA (NAME,OWNER,HOME,SENDER,WG_CODE,TASKS)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT OWNER (#PCDATA)>
<!ELEMENT HOME(#PCDATA)>
<!ELEMENT SENDER(#PCDATA)>
<!ELEMENT WG_CODE(#PCDATA)>

<!ELEMENT TASKS(TASK+,AGENT_CODE+)>
<!ATTLIST TASKS
  task CDATA #REQUIRED
  num CDATA #REQUIRED >

<!ELEMENT TASK(DATA*,FILE*)>
<!ATTLIST TASK
  num ID #REQUIRED
  return CDATA #IMPLIED
  server CDATA #REQUIRED 
  code_id CDATA #IMPLIED
  persistent CDATA #IMPLIED>

<!ELEMENT DATA (ROW*)>
<!ATTLIST DATA
  name CDATA #REQUIRED
  dim CDATA #REQUIRED
  type (char|short|int|float|double) #REQUIRED>

<!ELEMENT ROW (ROW*, #PCDATA)>
<!ATTLIST ROW
  index CDATA #REQUIRED>

<!ELEMENT FILE(#PCDATA)>
<!ATTLIST FILE
  name CDATA #REQUIRED>

<!ELEMENT AGENT_CODE (#PCDATA)>
<!ATTLIST AGENT_CODE
  id ID #IMPLIED >

=== Salmista-94/AgentOnMicrocontroller/demos/miscellaneous/simple_send/test_gettimeofday.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>mobagent1</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5050</HOME>
    <TASKS task="1" num="0">
     <TASK num="0" complete="0" server="localhost:5051">
       <DATA dim="0" name="no-return" >
       </DATA>
     </TASK>
     <AGENT_CODE>
      <![CDATA[
//#include <stdio.h>
#include <math.h>
struct mytime{
  unsigned long sec;
  long usec;
};

int main()
{
  struct mytime t;
    mc_gettimeofday(&t);
    printf("The time is %d, %d", t.sec, t.usec);
    printf("Hello World!\n");
    printf("This is mobagent1 from the agency at port 5050.\n");
    printf("I am performing the task on the agency at port 5051 now.\n");
    printf("%f\n", hypot(1,2)); 
    mc_gettimeofday(&t);
    printf("The time is %d, %d", t.sec, t.usec);
    return 0;
}
      ]]>
     </AGENT_CODE>
    </TASK>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/synchronization/mc_barrier_example/agent_1.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
  <MESSAGE message="MOBILE_AGENT">
    <MOBILE_AGENT>
     <AGENT_DATA>
       <NAME>agent1</NAME>
       <OWNER>IEL</OWNER>
       <HOME>localhost:5051</HOME>
       <TASKS task="1" num="0">
        <TASK num="0" complete="0" server="localhost:5050" persistent="1">
        </TASK>
	  <AGENT_CODE>
          <![CDATA[
#include <stdio.h>
#define MC_BARRIER_ID 56

int main()
{
    printf("Agent 1: Approaching Barrier 1...\n");
    mc_Barrier(MC_BARRIER_ID);
    printf("Agent 1: Past Barrier 1.\n");
    sleep( 10 );
    printf("Agent 1: At Barrier 2.\n");
    mc_Barrier(MC_BARRIER_ID + 1);
    printf("Agent 1: Past Barrier 2.\n");
    sleep( 10 );
    printf("Agent 1: At Barrier 3.\n");
    mc_Barrier(MC_BARRIER_ID + 2);
    printf("Agent 1: Past Barrier 3.\n");
    return 0;
}
        ]]>
        </AGENT_CODE>
      </TASKS>
      </AGENT_DATA>
    </MOBILE_AGENT>
  </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/agent_space_functionality/mc_df_service_test/service_provider_1.xml
<?xml version="1.0"?>
<!DOCTYPE myMessage SYSTEM "mobilec.dtd">
<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>service_provider_1</NAME> 
    <OWNER>IEL</OWNER> 
    <HOME>localhost:5051</HOME>
    <TASKS task="1" num="0">
     <TASK num="0"complete="0" server="localhost:5050" persistent="1" name="no-return">
     </TASK>
     <AGENT_CODE>
      <![CDATA[
#include <stdio.h>

int main() {
    char **services;
    int i;
    services = malloc(sizeof(char*)*2);
    for(i = 0; i < 2; i++) {
        services[i] = malloc(40);
    }
    strcpy(services[0], "addition");
    strcpy(services[1], "subtraction");
    printf("Service provider 1 has arrived.\n");
    printf("I provide addition and subtraction service.\n");
    mc_RegisterService( mc_current_agent, services, 2);
    return 0;
}

int addition(int a, int b) {
    printf("Adding %d and %d...\n", a, b);
    return a + b;
}

int subtraction(int a, int b) {
    printf("Subtracting %d - %d...\n", a, b);
    return a - b;
}
      ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/synchronization/cspace_cond_example/agent.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>agent</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5050</HOME>
    <TASKS task="1" num="0">
     <TASK num="0" complete="0" server="localhost:5051">
     </TASK>
     <AGENT_CODE>
      <![CDATA[
#include <stdio.h>
#define COND_ID 55
int main()
{
    int i;
    printf("This is agent 1.\n");
    for(i = 0; i < 5; i++) {
        printf("Agent: Perform some task here.\n");
        sleep(2);
        printf("Agent: signal C space for followup action.\n");
        mc_CondSignal(COND_ID);
        sleep(1);
    }

    return 0;
}
      ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/miscellaneous/steer_example/restart.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>restart_agent</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5051</HOME>
    <TASKS task="1" num="0">
     <TASK num="0"
           complete="0" 
           server="localhost:5050">
       <DATA name="no-return" >
       </DATA>
     </TASK>
      <AGENT_CODE>
       <![CDATA[
#include <stdio.h>
int main() {
    printf("Restarting...\n");
    mc_SendSteerCommand(MC_RESTART);
    return 0;
}
       ]]>
      </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/agent_space_functionality/mc_df_example/agent1.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
  <MESSAGE message="MOBILE_AGENT">
    <MOBILE_AGENT>
     <AGENT_DATA>
       <NAME>agent1</NAME>
       <OWNER>IEL</OWNER>
       <HOME>localhost:5050</HOME>
       <TASKS task="1" num="0">
        <TASK num="0" complete="0" server="localhost:5051" persistent="1" >
        </TASK>
	  <AGENT_CODE>
          <![CDATA[
#include <stdio.h>

int main()
{
    int i;
    char** services;
    services = (char**)malloc(sizeof(char*) * 2);
    for (i = 0; i < 2; i++) {
        services[i] = (char*)malloc(sizeof(char)*30);
    }
    strcpy(services[0], "agent1_service");
    strcpy(services[1], "agent1_bonus_service");

    mc_RegisterService(
            mc_current_agent,
            services,
            2
            );

    return 0;
}
        ]]>
        </AGENT_CODE>
      </TASKS>
      </AGENT_DATA>
    </MOBILE_AGENT>
  </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/miscellaneous/assembly_simulation/retrieval_agent.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>retrieval_agent</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5051</HOME>
    <TASKS task="1" num="0">
     <TASK num="0"complete="0" server="localhost:5052">
     </TASK>
     <AGENT_CODE>
      <![CDATA[
//#include <stdio.h>
#include <math.h>
int retval;
int main()
{
    printf("This is the retrieval agent.\n");
    printf("I am performing the task now.\n");
    retval = hypot(1,2);
    return 0;
}
      ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/miscellaneous/mc_get_agents_example/test2.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>mobagent2</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5125</HOME>
    <TASKS task="1" num="0">
     <TASK num="0" return="a" complete="0" server="localhost:5052" />
     <AGENT_CODE>
      <![CDATA[
#include <stdio.h>
#include <math.h>
double a;
int main()
{    
    printf("This is mobagent2 from the agency at port 5050.\n");
    a = 5.5;  
    printf("\n a = %f\n", a);
    return 0;
}
      ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>
