=== Salmista-94/AgentOnMicrocontroller/src/mobilec.dtd
<!ELEMENT MOBILEC_MESSAGE (MESSAGE)>
<!ELEMENT MESSAGE (MOBILE_AGENT|ENCRYPTED_DATA|ENCRYPTION_DATA)>
<!ATTLIST MESSAGE
  message (MOBILE_AGENT|RETURN_MSG|ENCRYPTED_DATA|ENCRYPTION_INITIALIZE) #REQUIRED>

<!ELEMENT MOBILE_AGENT (AGENT_DATA) >
<!ELEMENT AGENT_DATA (NAME,OWNER,HOME,SENDER,WG_CODE,TASKS)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT OWNER (#PCDATA)>
<!ELEMENT HOME(#PCDATA)>
<!ELEMENT SENDER(#PCDATA)>
<!ELEMENT WG_CODE(#PCDATA)>

<!ELEMENT TASKS(TASK+,AGENT_CODE+)>
<!ATTLIST TASKS
  task CDATA #REQUIRED
  num CDATA #REQUIRED >

<!ELEMENT TASK(DATA*,FILE*)>
<!ATTLIST TASK
  num ID #REQUIRED
  return CDATA #IMPLIED
  server CDATA #REQUIRED 
  code_id CDATA #IMPLIED
  persistent CDATA #IMPLIED>

<!ELEMENT DATA (ROW*)>
<!ATTLIST DATA
  name CDATA #REQUIRED
  dim CDATA #REQUIRED
  type (char|short|int|float|double) #REQUIRED>

<!ELEMENT ROW (ROW*, #PCDATA)>
<!ATTLIST ROW
  index CDATA #REQUIRED>

<!ELEMENT FILE(#PCDATA)>
<!ATTLIST FILE
  name CDATA #REQUIRED>

<!ELEMENT AGENT_CODE (#PCDATA)>
<!ATTLIST AGENT_CODE
  id ID #IMPLIED >

=== Salmista-94/AgentOnMicrocontroller/demos/miscellaneous/agent_squad_test/squad_leader.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>squad_leader</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5050</HOME>
    <TASKS task="3" num="0">
      <TASK  num="0"
             complete="0" 
             server="localhost:5051">
      </TASK>
      <TASK  num="1"
             complete="0" 
             server="localhost:5052">
      </TASK>
      <TASK  num="2"
             complete="0" 
             server="localhost:5053">
      </TASK>

     <AGENT_CODE>
       <![CDATA[
#include <stdio.h>
#define AGENTS_BEGIN 55
#define AGENTS_END 56
#define TASK_BEGIN 57
#define TASK1 58
#define TASK2 59
#define TASK3 60
#define NUM_AGENTS 4
int main() 
{
    mc_BarrierInit(AGENTS_BEGIN, NUM_AGENTS);
    mc_BarrierInit(AGENTS_END, NUM_AGENTS);
    sleep(1);
    if (mc_host_port == 5051) {
        printf("Squad leader at port %d. Setting up barriers.\n",
                mc_host_port);
        mc_Barrier(AGENTS_BEGIN);
        mc_Barrier(AGENTS_END);
    } else if (mc_host_port == 5052) {
        printf("Squad leader at port %d. Setting up barriers.\n",
                mc_host_port);
        mc_Barrier(AGENTS_BEGIN);
        mc_Barrier(AGENTS_END);
    } else if (mc_host_port = 5053) {
        printf("Squad leader at port %d. Setting up barriers.\n",
                mc_host_port);
        mc_BarrierInit(TASK_BEGIN, 3);
        mc_BarrierInit(TASK1, 2);
        mc_BarrierInit(TASK2, 2);
        mc_BarrierInit(TASK3, 2);
        mc_Barrier(AGENTS_BEGIN);
        mc_Barrier(TASK_BEGIN);
        mc_Barrier(AGENTS_END);
    }
    return 0;
}
       ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/miscellaneous/simple_send/template_racer.xml
<?xml version="1.0"?>
<!DOCTYPE myMessage SYSTEM "mobilec.dtd">
<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>TEMPLATE_AGENT_NAME</NAME>
    <OWNER>IEL</OWNER>
    <HOME>bird2.engr.ucdavis.edu:5050</HOME>
    <TASKS task="4" num="0">
     <TASK num="0" server="TEMPLATE_SERVER1" code_id="0">
       <DATA dim="0" name="no-return" complete="0" />
     </TASK>

     <TASK num="1" server="TEMPLATE_SERVER2" code_id="1" >
       <DATA dim="0" name="no-return" complete="0" />
     </TASK>

     <TASK num="2" server="TEMPLATE_SERVER3" code_id="1">
       <DATA dim="0" name="no-return" complete="0" />
     </TASK>

     <TASK num="3" server="TEMPLATE_SERVER4" code_id="2">
       <DATA dim="0" name="no-return" complete="0" />
     </TASK>
     <AGENT_CODE id="0">
      <![CDATA[
#include <stdio.h>
#define COND_1 TEMPLATE_COND1
#define COND_2 TEMPLATE_COND2 
int main() {
  printf("This is TEMPLATE_AGENT_NAME.\n");
  mc_CondWait(COND_1);
  mc_CondReset(COND_1);
  mc_CondSignal(COND_2);
  return 0;
}
      ]]>
     </AGENT_CODE>
     <AGENT_CODE id="1">
      <![CDATA[
#include <stdio.h>
#define COND_1 TEMPLATE_COND1
#define COND_2 TEMPLATE_COND2
int main() {
  printf("This is TEMPLATE_AGENT_NAME.\n");
  mc_CondSignal(COND_1);
  mc_CondWait(COND_2);
  mc_CondReset(COND_2);

  mc_CondWait(COND_1);
  mc_CondReset(COND_1);
  mc_CondSignal(COND_2);
  return 0;
}
      ]]>
     </AGENT_CODE>
     <AGENT_CODE id="2">
      <![CDATA[
#include <stdio.h>
#define COND_1 TEMPLATE_COND1
#define COND_2 TEMPLATE_COND2 
int main() {
  printf("This is TEMPLATE_AGENT_NAME.\n");
  mc_CondSignal(COND_1);
  mc_CondWait(COND_2);
  mc_CondReset(COND_2);
  return 0;
}
      ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/miscellaneous/mc_sample_app/korebot/mobagent2.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">
<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>mobagent2</NAME>
    <OWNER>IEL</OWNER>
    <HOME>10.0.0.11:5050</HOME>
    <TASK task="1" num="0">
     <DATA number_of_elements="0" 
           name="no-return" 
           complete="0" 
           server="10.0.0.15:5050">
     </DATA>
     <AGENT_CODE>
      <![CDATA[
int main() {
  MCAgent_t agent;
   
  agent = mc_FindAgentByName("mobagent1");
  if(agent != NULL) {
    mc_SetAgentStatus(agent, MC_AGENT_NEUTRAL);
  }

  return 0;
}
      ]]>
     </AGENT_CODE>
    </TASK>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/miscellaneous/mc_sample_app/key.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="KEY">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>mobagent1</NAME>
    <OWNER>IEL</OWNER>
    <HOME>bird1.engr.ucdavis.edu:5050</HOME>
    <TASK task="1" num="0">
     <DATA name="no-return" 
           complete="0" 
           server="iel2.engr.ucdavis.edu:5130">
     </DATA>
     <KEY>
     1421314241
     </KEY>
    </TASK>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/agent_space_functionality/mc_df_service_test/test1.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
  <MESSAGE message="MOBILE_AGENT">
    <MOBILE_AGENT>
     <AGENT_DATA>
       <NAME>mobagent1</NAME>
       <OWNER>IEL</OWNER>
       <HOME>localhost:5051</HOME>
       <TASKS task="1" num="0">
        <TASK num="0" complete="0" server="127.0.0.1:5050">
        </TASK>
	  <AGENT_CODE>
          <![CDATA[
#include <stdio.h>
int main()
{
    MCAgent_t agent;
    int retval;
    /* Search Return Variables */
    char** agentNames;
    char** serviceNames;
    int *agentIDs;
    int numResults;
    int a, b;

    /* Search for addition service */
    printf("\n\n\nSearching for addition service.\n");
    mc_SearchForService(
            "addition", 
            &agentNames,
            &serviceNames,
            &agentIDs,
            &numResults );
    printf("Done searching.\n");
    if (numResults < 1) {
        printf("No agents with service 'addition' found.\n");
        exit(0);
    }

    /* Just get the first hit */
    printf("Using agent %s for addition.\n", agentNames[0]); 
    agent = mc_FindAgentByID(agentIDs[0]);
    
    a = 44;
    b = 45;
    mc_CallAgentFunc(agent, "addition", &retval, a, b);
    printf("Result of addition %d + %d is %d.\n", a, b, retval);

    /* Now search for multiplication service */
    printf("\n\n Searching for Multiplication service...\n");
    mc_SearchForService(
            "multiplication",
            &agentNames,
            &serviceNames,
            &agentIDs,
            &numResults );

    if (numResults < 1) {
        printf("No agents with service 'multiplication' found.\n");
        exit(0);
    }

    printf("Using agent %s for multiplication.\n", agentNames[0]);
    agent = mc_FindAgentByID(agentIDs[0]);
    mc_CallAgentFunc(agent, "multiplication", &retval, a, b);
    printf("Result of multiplication %d * %d is %d.\n", a, b, retval);

    /* Now lets try to deregister a service */
    mc_DeregisterService(
            agentIDs[0],
            serviceNames[0]
            );
    
    return 0;
}
        ]]>
        </AGENT_CODE>
      </TASKS>
      </AGENT_DATA>
    </MOBILE_AGENT>
  </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/synchronization/agent_mutex_example/wake.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>wake_agent</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5050</HOME>
    <TASKS task="1" num="0">
     <TASK num="0" complete="0" server="localhost:5051">
     </TASK>
     <AGENT_CODE>
      <![CDATA[
#include <stdio.h>
int main()
{
    int mutex_id;
    mutex_id = 55;
    printf("Agent 2: Has arrived");
    printf("Agent 2: Attempting to lock the mutex...\n");
    mc_MutexLock(mutex_id);
    printf("Agent 2: Mutex locked.\n");
    printf("Agent 2: Perform protected operations here.\n");
    sleep(5);
    mc_MutexUnlock(mutex_id);
    printf("Agent 2: Mutex Unlocked\n");
    mc_SyncDelete(mutex_id);

    return 0;
}
      ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/synchronization/agent_cond_example/sleep.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>sleep_agent</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5050</HOME>
    <TASKS task="1" num="0">
     <TASK num="0" complete="0" server="localhost:5051">
     </TASK>
     <AGENT_CODE>
      <![CDATA[
#include <stdio.h>

#define SYNC_ID 55
int main()
{
    int cond_id;
    printf("Sleep agent has arrived.\n");
    cond_id = mc_SyncInit(SYNC_ID);
    if (cond_id != SYNC_ID) {
        printf("Possible error. Aborting...\n");
        exit(1);
    }
    printf("This is the sleep agent.\n");
    printf("I am going to sleep now...\n");
    mc_CondWait(cond_id);
    printf("This is the sleep agent: I am awake now. Continuing...\n");
    mc_SyncDelete(cond_id);

    return 0;
}
      ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/miscellaneous/agent_squad_test/agent2.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>agent2</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5050</HOME>
    <TASKS task="3" num="0">
     <TASK num="0"
           complete="0" 
           server="localhost:5051">
     </TASK>
     <TASK num="1"
           complete="0" 
           server="localhost:5052">
     </TASK>
     <TASK num="2"
           complete="0" 
           server="localhost:5053">
     </TASK>

     <AGENT_CODE>
       <![CDATA[
#include <stdio.h>
#include <time.h>
#define AGENTS_BEGIN 55
#define AGENTS_END 56
#define TASK_BEGIN 57
#define TASK1 58
#define TASK2 59
#define TASK3 60

int main() {
    while (mc_Barrier(AGENTS_BEGIN) == MC_ERR_NOT_FOUND) {
        sleep(1);
    }
    srand(time(NULL));
    if( mc_host_port == 5052) {
        printf("Agent 2: Beginning task on port %d.\n",
                mc_host_port);
        sleep( rand() % 10 );
        printf("Agent 2: Task finished.");
    }  else {
        printf("Agent 2: Arrived at port %d: Nothing to do.\n",
                mc_host_port);
    }

    while(mc_Barrier(AGENTS_END) == MC_ERR_NOT_FOUND) {
        sleep(1);
    }
    return 0;
}
       ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>
