=== Salmista-94/AgentOnMicrocontroller/src/mobilec.dtd
<!ELEMENT MOBILEC_MESSAGE (MESSAGE)>
<!ELEMENT MESSAGE (MOBILE_AGENT|ENCRYPTED_DATA|ENCRYPTION_DATA)>
<!ATTLIST MESSAGE
  message (MOBILE_AGENT|RETURN_MSG|ENCRYPTED_DATA|ENCRYPTION_INITIALIZE) #REQUIRED>

<!ELEMENT MOBILE_AGENT (AGENT_DATA) >
<!ELEMENT AGENT_DATA (NAME,OWNER,HOME,SENDER,WG_CODE,TASKS)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT OWNER (#PCDATA)>
<!ELEMENT HOME(#PCDATA)>
<!ELEMENT SENDER(#PCDATA)>
<!ELEMENT WG_CODE(#PCDATA)>

<!ELEMENT TASKS(TASK+,AGENT_CODE+)>
<!ATTLIST TASKS
  task CDATA #REQUIRED
  num CDATA #REQUIRED >

<!ELEMENT TASK(DATA*,FILE*)>
<!ATTLIST TASK
  num ID #REQUIRED
  return CDATA #IMPLIED
  server CDATA #REQUIRED 
  code_id CDATA #IMPLIED
  persistent CDATA #IMPLIED>

<!ELEMENT DATA (ROW*)>
<!ATTLIST DATA
  name CDATA #REQUIRED
  dim CDATA #REQUIRED
  type (char|short|int|float|double) #REQUIRED>

<!ELEMENT ROW (ROW*, #PCDATA)>
<!ATTLIST ROW
  index CDATA #REQUIRED>

<!ELEMENT FILE(#PCDATA)>
<!ATTLIST FILE
  name CDATA #REQUIRED>

<!ELEMENT AGENT_CODE (#PCDATA)>
<!ATTLIST AGENT_CODE
  id ID #IMPLIED >

=== Salmista-94/AgentOnMicrocontroller/demos/synchronization/agent_cond_example/wake.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>wake_agent</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5050</HOME>
    <TASKS task="1" num="0">
     <TASK num="0" complete="0" server="localhost:5051">
     </TASK>
     <AGENT_CODE>
      <![CDATA[
#include <stdio.h>

#define SYNC_ID 55
int main()
{
    int cond_id;
    int err;
    cond_id = SYNC_ID;
    printf("This is the wake agent.\n");
    err = mc_CondSignal(cond_id);
    if(err) {
      printf("Error signalling condition variable!\n");
    }

    return 0;
}
      ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/miscellaneous/agent_squad_test/agent1.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>agent1</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5050</HOME>
    <TASKS task="3" num="0">
     <TASK num="0"
           complete="0" 
           server="localhost:5051">
     </TASK>
     <TASK num="1"
           complete="0" 
           server="localhost:5052">
     </TASK>
     <TASK num="2"
           complete="0" 
           server="localhost:5053">
     </TASK>

     <AGENT_CODE>
       <![CDATA[
#include <stdio.h>
#include <time.h>
#define AGENTS_BEGIN 55
#define AGENTS_END 56
#define TASK_BEGIN 57
#define TASK1 58
#define TASK2 59
#define TASK3 60

int main() {
    while (mc_Barrier(AGENTS_BEGIN) == MC_ERR_NOT_FOUND) {
        printf("sleeping...\n");
        sleep(1);
    }
    srand(time(NULL));
    if( mc_host_port == 5051) {
        printf("Agent 1: Beginning task on port %d.\n",
                mc_host_port);
        sleep( rand() % 10 );
        printf("Agent 1: Task finished.");
    } else if (mc_host_port == 5053) {
        /* Coordinate with agent 3 to perform 3 tasks. */
        while( mc_Barrier(TASK_BEGIN) == MC_ERR_NOT_FOUND ) {
            sleep(1);
        }
        printf("Agent 1: Begin Task 1.\n");
        sleep(rand()%10);
        printf("Agent 1: End task 1.\n");
        mc_Barrier(TASK1);
        printf("Agent 1: Begin Task 2.\n");
        sleep(rand()%10);
        printf("Agent 1: End task 2.\n");
        mc_Barrier(TASK2);
        printf("Agent 1: Begin Task 3.\n");
        sleep(rand()%10);
        printf("Agent 1: End task 3.\n");
        mc_Barrier(TASK3);
    } else {
        printf("Agent 1: Arrived at port %d: Nothing to do.\n",
                mc_host_port);
    }

    while(mc_Barrier(AGENTS_END) == MC_ERR_NOT_FOUND) {
        sleep(1);
    }
    return 0;
}
       ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/synchronization/agent_mutex_example/sleep.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>sleep_agent</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5050</HOME>
    <TASKS task="1" num="0">
     <TASK num="0" complete="0" server="localhost:5051">
     </TASK>
     <AGENT_CODE>
      <![CDATA[
#include <stdio.h>
int main()
{
    int mutex_id;
    printf("Sleep agent has arrived.\n");
    mutex_id = mc_SyncInit(55);
    if (mutex_id != 55) {
        printf("Possible error. Aborting...\n");
        exit(1);
    }
    printf("This is agent 1.\n");
    printf("Agent 1: I am locking the mutex now.\n");
    mc_MutexLock(mutex_id);
    printf("Agent 1: Mutex locked. Perform protected operations here\n");
    printf("Agent 1: Waiting for 5 seconds...\n");
    sleep(5);
    printf("Agent 1: Unlocking mutex now...\n");
    mc_MutexUnlock(mutex_id);

    return 0;
}
      ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/miscellaneous/mc_sample_app/test1.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>mobagent1</NAME>
    <OWNER>IEL</OWNER>
    <HOME>169.237.108.153:5051</HOME>
    <TASKS task="1" num="0">
     <TASK num="0" complete="0" server="169.237.108.153:5050">
     </TASK>
     <AGENT_CODE>
      <![CDATA[
#include <stdio.h>
int main() {
  printf("Hello World ... 1 !\n");
  sleep(20);
  return 0;
}
      ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/getting_started/bluetooth/test1.xml
<!-- File: hello_world/test1.xml -->

<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>mobagent1</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5050</HOME>
		<WG_CODE>test_workgroup</WG_CODE>
    <TASKS task="1" num="0">
     <TASK num="0" return="no-return" complete="0" server="localhost:5051" />
     <AGENT_CODE>
      <![CDATA[
/*#define A 2*/
#include <stdio.h>
#include <math.h>
int main()
{
    char* str;
    printf("Hello World!\n");
    printf("This is mobagent1 from the agency at port 5050.\n");
    printf("I am performing the task on the agency at port 5051 now.\n");
    printf("%f\n", hypot(1,2)); 

    return 0;
}
      ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>
<!-- File: hello_world/test1.xml -->

<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>mobagent1</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5050</HOME>
		<WG_CODE>test_workgroup</WG_CODE>
    <TASKS task="1" num="0">
     <TASK num="0" return="no-return" complete="0" server="localhost:5051" />
     <AGENT_CODE>
      <![CDATA[
/*#define A 2*/
#include <stdio.h>
#include <math.h>
int main()
{
    char* str;
    printf("Hello World!\n");
    printf("This is mobagent1 from the agency at port 5050.\n");
    printf("I am performing the task on the agency at port 5051 now.\n");
    printf("%f\n", hypot(1,2)); 

    return 0;
}
      ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/synchronization/cspace_mutex_example/agent.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>sleep_agent</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5050</HOME>
    <TASKS task="1" num="0">
     <TASK num="0"complete="0" server="localhost:5051">
       <DATA dim="0" name="no-return" >
       </DATA>
     </TASK>
     <AGENT_CODE>
      <![CDATA[
#include <stdio.h>
int main()
{
    int mutex_id;
    int i;
    printf("This is agent 1.\n");
    for(i = 0; i < 10; i++) {
        printf("Agent: Attempting to lock mutex...\n");
        mc_MutexLock(55);
        printf("Agent: Mutex Locked. Performing protected operations...\n");
        sleep(1);
        printf("Agent: Attempting to unlock mutex...\n");
        mc_MutexUnlock(55);
        printf("Agent: Mutex Unlocked.\n");
    }

    return 0;
}
      ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/agent_space_functionality/mc_df_example/agent3.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
  <MESSAGE message="MOBILE_AGENT">
    <MOBILE_AGENT>
     <AGENT_DATA>
       <NAME>agent3</NAME>
       <OWNER>IEL</OWNER>
       <HOME>localhost:5050</HOME>
       <TASKS task="1" num="0">
        <TASK num="0" complete="0" server="localhost:5051" persistent="1" >
        </TASK>
	  <AGENT_CODE>
          <![CDATA[
#include <stdio.h>

int main()
{
    int i;
    char **agentNames;
    char **serviceNames;
    int *agentIDs;
    int numResults;

    mc_SearchForService(
            "bonus",
            &agentNames,
            &serviceNames,
            &agentIDs,
            &numResults
            );
    for (i = 0; i < numResults; i++) {
        printf("%s:%d %s\n",
                agentNames[i],
                agentIDs[i],
                serviceNames[i]
              );
    }

    printf("\n");

    return 0;
}
        ]]>
        </AGENT_CODE>
      </TASKS>
      </AGENT_DATA>
    </MOBILE_AGENT>
  </MESSAGE>
</MOBILEC_MESSAGE>

=== Salmista-94/AgentOnMicrocontroller/demos/agent_migration_message_format/mc_migration_message_example/test1.xml
<?xml version="1.0"?>

<!DOCTYPE myMessage SYSTEM "mobilec.dtd">

<MOBILEC_MESSAGE>
 <MESSAGE message="MOBILE_AGENT">
  <MOBILE_AGENT>
   <AGENT_DATA>
    <NAME>mobagent1</NAME>
    <OWNER>IEL</OWNER>
    <HOME>localhost:5050</HOME>
    <TASKS task="1" num="0">
     <TASK dim="0" name="no-return" complete="0" server="localhost:5051" />
     <AGENT_CODE>
      <![CDATA[
//#include <stdio.h>
#include <math.h>
int main()
{
    char* str;
    printf("Hello World!\n");
    printf("This is mobagent1 from the agency at port 5050.\n");
    printf("I am performing the task on the agency at port 5051 now.\n");
    printf("%f\n", hypot(1,2)); 
    str = strdup("Hello! This is a test.");
    free(str);

    return 0;
}
      ]]>
     </AGENT_CODE>
    </TASKS>
   </AGENT_DATA>
  </MOBILE_AGENT>
 </MESSAGE>
</MOBILEC_MESSAGE>
